name: Deploy to Client's Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.THINGSBOARD_SSH }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 192.168.29.32 >> ~/.ssh/known_hosts

    - name: Deploy Backend
      run: |
        ssh -T thingsboard1@192.168.29.32 <<EOF
          mkdir -p /var/www/client2_backend
          cat > /var/www/client2_backend/.env <<EOL
          $CLIENT1_ENV
          EOL
          cd /var/www/client2_backend
          npm install
          pm2 restart app.js || pm2 start app.js
        EOF
      env:
        CLIENT1_ENV: ${{ secrets.CLIENT1_ENV }}
